version: 2.1

# ############################################
#
# Set Circle CI Reusable Commands
#
# For more information, see the documentation:
# https://circleci.com/docs/2.0/reusing-config
#
# ############################################
commands:
  run-python-tests:
    description: "Run Tox based Python tests"
    parameters:
      tox-env:
        type: string
    steps:
      - checkout
      - run:
          name: Install Tox
          command: sudo pip install tox
      - run:
          name: Run linter
          command: tox -e lint
      - run:
          name: Run unit tests
          command: tox -e << parameters.tox-env >>

# ###############################
#
# CircleCI 2.1 Jobs
#
# ###############################
jobs:
  tests-passed:
    description: "Gate to wait for all tests to pass"
    docker:
      - image: bash:latest
    steps:
      - run: echo "All tests passed"

  python-34-test:
    docker:
      - image: circleci/python:3.4
    steps:
      - run-python-tests:
          tox-env: "py34"

  python-35-test:
    docker:
      - image: circleci/python:3.5
    steps:
      - run-python-tests:
          tox-env: "py35"

  python-36-test:
    docker:
      - image: circleci/python:3.6
    steps:
      - run-python-tests:
          tox-env: "py36"

  python-37-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - run-python-tests:
          tox-env: "py37"

  python-38-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - run-python-tests:
          tox-env: "py38"

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Write VERSION file
          command: echo $(git describe --tags --exact-match $(git rev-parse --short=7 HEAD)) > reeeeeeeeee/VERSION
      - run:
          name: Build Packages
          command: |
            sudo pip install twine wheel
            mv setup.py setup.bak
            EEEEE="ree"
            for i in $(seq 3 24); do
                EEEEE="${EEEEE}e"
                sed "s/name=\"reeeeeeeeee\",/name=\"${EEEEE}\",/" setup.bak > setup.py
                python setup.py sdist bdist_wheel
            done
      - run:
          name: Upload packages
          command: twine upload --verbose -u $PYPI_USER -p $PYPI_PASS dist/reee*


# ###############################
#
# CircleCI Job Filters
#
# ###############################
test-filters: &test-filters
  tags:
    only: /.*/
  branches:
    only: /.*/

deploy-filters: &deploy-filters
  tags:
    only: /.*/
  branches:
    ignore: /.*/

# ###############################
#
# CircleCI Workflow
#
# ###############################
workflows:
  version: 2.1

  reeeeeeeeee-pipeline:
    jobs:
      - python-34-test:
          filters: *test-filters
      - python-35-test:
          filters: *test-filters
      - python-36-test:
          filters: *test-filters
      - python-37-test:
          filters: *test-filters
      - python-38-test:
          filters: *test-filters
      - tests-passed:
          requires:
            - python-34-test
            - python-35-test
            - python-36-test
            - python-37-test
            - python-38-test
          filters: *test-filters
      - deploy:
          requires:
            - tests-passed
          filters: *deploy-filters
